---
apiVersion: v1
kind: Service
metadata:
  name: p2w-client
  labels:
    app: p2w-client
spec:
  ports:
    - port: 8001
      name: http
      protocol: TCP
  clusterIP: None
  selector:
    app: p2w-client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p2w-client
spec:
  selector:
    matchLabels:
      app: p2w-client
  serviceName: p2w-client
  replicas: 1
  template:
    metadata:
      labels:
        app: p2w-client
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
        - name: p2w-client
          image: p2w-client
          command:
            - python3
            - /usr/src/pyth/p2w_autoattest.py
          tty: true
          readinessProbe:
            tcpSocket:
              port: 2000
            periodSeconds: 1
            failureThreshold: 300
