---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terra-lcd
  name: terra-lcd
spec:
  ports:
  - name: lcd
    port: 1317
    protocol: TCP
  selector:
    app: terra-lcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terra-terrad
  name: terra-terrad
spec:
  ports:
  - name: rpc
    port: 26657
    protocol: TCP
  selector:
    app: terra-terrad
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terra-fcd
  name: terra-fcd
spec:
  ports:
    - name: fcd
      port: 3060
      protocol: TCP
  selector:
    app: terra-fcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: terra-lcd
  name: terra-lcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-lcd
  template:
    metadata:
      labels:
        app: terra-lcd
    spec:
      containers:
      - args:
        - terracli
        - rest-server
        - --laddr=tcp://0.0.0.0:1317
        - --node=tcp://terra-terrad:26657
        - --trust-node=true
        - --unsafe-cors
        image: terra-image
        name: terra-lcd
        ports:
        - containerPort: 1317
        readinessProbe:
          tcpSocket:
            port: 1317
      restartPolicy: Always
  serviceName: terra-lcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: terra-terrad
  name: terra-terrad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-terrad
  template:
    metadata:
      labels:
        app: terra-terrad
    spec:
      containers:
      - args:
        - terrad
        - start
        image: terra-image
        name: terra-terrad
        ports:
        - containerPort: 26657
        readinessProbe:
          httpGet:
            port: 26657
        resources: {}
      - name: terra-contracts
        image: terra-contracts
      restartPolicy: Always
  serviceName: terra-terrad
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: terra-fcd
  name: terra-fcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-fcd
  template:
    metadata:
      labels:
        app: terra-fcd
    spec:
      containers:
        - image: postgres:12
          name: fcd-postgres
          ports:
            - containerPort: 5432
          resources: {}
          env:
            - name: POSTGRES_USER
              value: dev
            - name: POSTGRES_PASSWORD
              value: dev
            - name: POSTGRES_DB
              value: fcd
        - image: terramoney/fcd:0.10.8
          name: fcd-collector
          args:
            - collector
          resources: { }
          env:
            - name: CHAIN_ID
              value: localterra
            - name: LCD_URI
              value: http://terra-lcd:1317
            - name: BYPASS_URI
              value: http://terra-lcd:1317
            - name: RPC_URI
              value: http://terra-terrad:26657
            - name: TYPEORM_CONNECTION
              value: postgres
            - name: TYPEORM_HOST
              value: localhost
            - name: TYPEORM_USERNAME
              value: dev
            - name: TYPEORM_PASSWORD
              value: dev
            - name: TYPEORM_DATABASE
              value: fcd
            - name: TYPEORM_SYNCHRONIZE
              value: "true"
            - name: TYPEORM_LOGGING
              value: "false"
            - name: TYPEORM_ENTITIES
              value: "src/orm/*Entity.ts"
        - image: terramoney/fcd:0.10.8
          name: fcd-api
          args:
            - start
          resources: { }
          ports:
            - containerPort: 3060
          env:
            - name: CHAIN_ID
              value: localterra
            - name: LCD_URI
              value: http://terra-lcd:1317
            - name: BYPASS_URI
              value: http://terra-lcd:1317
            - name: RPC_URI
              value: http://terra-terrad:26657
            - name: TYPEORM_CONNECTION
              value: postgres
            - name: TYPEORM_HOST
              value: localhost
            - name: TYPEORM_USERNAME
              value: dev
            - name: TYPEORM_PASSWORD
              value: dev
            - name: TYPEORM_DATABASE
              value: fcd
            - name: TYPEORM_SYNCHRONIZE
              value: "true"
            - name: TYPEORM_LOGGING
              value: "false"
            - name: TYPEORM_ENTITIES
              value: "src/orm/*Entity.ts"
      restartPolicy: Always
  serviceName: terra-fcd
